macro_rules! cities {
    ($($variant:ident => ($name:expr, $province:expr)),+ $(,)?) => {
        /// 城市表按行政区划保持完整，具体哪些能查取决于 provider 覆盖到哪些，
        /// 因此会有一些暂时用不到的取值。
        #[allow(dead_code)]
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
        pub enum City {
            $($variant),+
        }

        impl City {
            pub const fn name(&self) -> &'static str {
                match self {
                    $(Self::$variant => $name),+
                }
            }

            pub const fn province(&self) -> &'static str {
                match self {
                    $(Self::$variant => $province),+
                }
            }
        }
    };
}

cities! {
    // 直辖市
    Beijing => ("北京", "直辖市"),
    Tianjin => ("天津", "直辖市"),
    Shanghai => ("上海", "直辖市"),
    Chongqing => ("重庆", "直辖市"),
    // 河北
    Shijiazhuang => ("石家庄", "河北"),
    Tangshan => ("唐山", "河北"),
    Qinhuangdao => ("秦皇岛", "河北"),
    Handan => ("邯郸", "河北"),
    Xingtai => ("邢台", "河北"),
    Baoding => ("保定", "河北"),
    Zhangjiakou => ("张家口", "河北"),
    Chengde => ("承德", "河北"),
    Cangzhou => ("沧州", "河北"),
    Langfang => ("廊坊", "河北"),
    Hengshui => ("衡水", "河北"),
    // 山西
    Taiyuan => ("太原", "山西"),
    Datong => ("大同", "山西"),
    Yangquan => ("阳泉", "山西"),
    Changzhi => ("长治", "山西"),
    Jincheng => ("晋城", "山西"),
    Shuozhou => ("朔州", "山西"),
    Jinzhong => ("晋中", "山西"),
    Yuncheng => ("运城", "山西"),
    Xinzhou => ("忻州", "山西"),
    Linfen => ("临汾", "山西"),
    Lvliang => ("吕梁", "山西"),
    // 内蒙古
    Hohhot => ("呼和浩特", "内蒙古"),
    Baotou => ("包头", "内蒙古"),
    Wuhai => ("乌海", "内蒙古"),
    Chifeng => ("赤峰", "内蒙古"),
    Tongliao => ("通辽", "内蒙古"),
    Ordos => ("鄂尔多斯", "内蒙古"),
    Hulunbuir => ("呼伦贝尔", "内蒙古"),
    Bayannur => ("巴彦淖尔", "内蒙古"),
    Ulanqab => ("乌兰察布", "内蒙古"),
    // 辽宁
    Shenyang => ("沈阳", "辽宁"),
    Dalian => ("大连", "辽宁"),
    Anshan => ("鞍山", "辽宁"),
    Fushun => ("抚顺", "辽宁"),
    Benxi => ("本溪", "辽宁"),
    Dandong => ("丹东", "辽宁"),
    Jinzhou => ("锦州", "辽宁"),
    Yingkou => ("营口", "辽宁"),
    Fuxin => ("阜新", "辽宁"),
    Liaoyang => ("辽阳", "辽宁"),
    Panjin => ("盘锦", "辽宁"),
    Tieling => ("铁岭", "辽宁"),
    ChaoyangLN => ("朝阳", "辽宁"),
    Huludao => ("葫芦岛", "辽宁"),
    // 吉林
    Changchun => ("长春", "吉林"),
    JilinCity => ("吉林", "吉林"),
    Siping => ("四平", "吉林"),
    Liaoyuan => ("辽源", "吉林"),
    Tonghua => ("通化", "吉林"),
    Baishan => ("白山", "吉林"),
    Songyuan => ("松原", "吉林"),
    Baicheng => ("白城", "吉林"),
    // 黑龙江
    Harbin => ("哈尔滨", "黑龙江"),
    Qiqihar => ("齐齐哈尔", "黑龙江"),
    Jixi => ("鸡西", "黑龙江"),
    Hegang => ("鹤岗", "黑龙江"),
    Shuangyashan => ("双鸭山", "黑龙江"),
    Daqing => ("大庆", "黑龙江"),
    Yichun => ("伊春", "黑龙江"),
    Jiamusi => ("佳木斯", "黑龙江"),
    Mudanjiang => ("牡丹江", "黑龙江"),
    Heihe => ("黑河", "黑龙江"),
    Suihua => ("绥化", "黑龙江"),
    // 江苏
    Nanjing => ("南京", "江苏"),
    Wuxi => ("无锡", "江苏"),
    Xuzhou => ("徐州", "江苏"),
    Changzhou => ("常州", "江苏"),
    Suzhou => ("苏州", "江苏"),
    Nantong => ("南通", "江苏"),
    Lianyungang => ("连云港", "江苏"),
    Huaian => ("淮安", "江苏"),
    Yancheng => ("盐城", "江苏"),
    Yangzhou => ("扬州", "江苏"),
    Zhenjiang => ("镇江", "江苏"),
    Taizhou => ("泰州", "江苏"),
    Suqian => ("宿迁", "江苏"),
    // 浙江
    Hangzhou => ("杭州", "浙江"),
    Ningbo => ("宁波", "浙江"),
    Wenzhou => ("温州", "浙江"),
    Jiaxing => ("嘉兴", "浙江"),
    Huzhou => ("湖州", "浙江"),
    Shaoxing => ("绍兴", "浙江"),
    Jinhua => ("金华", "浙江"),
    Quzhou => ("衢州", "浙江"),
    Zhoushan => ("舟山", "浙江"),
    TaizhouZJ => ("台州", "浙江"),
    Lishui => ("丽水", "浙江"),
    // 安徽
    Hefei => ("合肥", "安徽"),
    Wuhu => ("芜湖", "安徽"),
    Bengbu => ("蚌埠", "安徽"),
    Huainan => ("淮南", "安徽"),
    Maanshan => ("马鞍山", "安徽"),
    Huaibei => ("淮北", "安徽"),
    Tongling => ("铜陵", "安徽"),
    Anqing => ("安庆", "安徽"),
    Huangshan => ("黄山", "安徽"),
    Chuzhou => ("滁州", "安徽"),
    Fuyang => ("阜阳", "安徽"),
    SuzhouAH => ("宿州", "安徽"),
    Luan => ("六安", "安徽"),
    Bozhou => ("亳州", "安徽"),
    Chizhou => ("池州", "安徽"),
    Xuancheng => ("宣城", "安徽"),
    // 福建
    Fuzhou => ("福州", "福建"),
    Xiamen => ("厦门", "福建"),
    Putian => ("莆田", "福建"),
    Sanming => ("三明", "福建"),
    Quanzhou => ("泉州", "福建"),
    Zhangzhou => ("漳州", "福建"),
    Nanping => ("南平", "福建"),
    Longyan => ("龙岩", "福建"),
    Ningde => ("宁德", "福建"),
    // 江西
    Nanchang => ("南昌", "江西"),
    Jingdezhen => ("景德镇", "江西"),
    Pingxiang => ("萍乡", "江西"),
    Jiujiang => ("九江", "江西"),
    Xinyu => ("新余", "江西"),
    Yingtan => ("鹰潭", "江西"),
    Ganzhou => ("赣州", "江西"),
    Jian => ("吉安", "江西"),
    YichunJX => ("宜春", "江西"),
    FuzhouJX => ("抚州", "江西"),
    Shangrao => ("上饶", "江西"),
    // 山东
    Jinan => ("济南", "山东"),
    Qingdao => ("青岛", "山东"),
    Zibo => ("淄博", "山东"),
    Zaozhuang => ("枣庄", "山东"),
    Dongying => ("东营", "山东"),
    Yantai => ("烟台", "山东"),
    Weifang => ("潍坊", "山东"),
    Jining => ("济宁", "山东"),
    Taian => ("泰安", "山东"),
    Weihai => ("威海", "山东"),
    Rizhao => ("日照", "山东"),
    Linyi => ("临沂", "山东"),
    Dezhou => ("德州", "山东"),
    Liaocheng => ("聊城", "山东"),
    Binzhou => ("滨州", "山东"),
    Heze => ("菏泽", "山东"),
    // 河南
    Zhengzhou => ("郑州", "河南"),
    Kaifeng => ("开封", "河南"),
    Luoyang => ("洛阳", "河南"),
    Pingdingshan => ("平顶山", "河南"),
    Anyang => ("安阳", "河南"),
    Hebi => ("鹤壁", "河南"),
    Xinxiang => ("新乡", "河南"),
    Jiaozuo => ("焦作", "河南"),
    Puyang => ("濮阳", "河南"),
    Xuchang => ("许昌", "河南"),
    Luohe => ("漯河", "河南"),
    Sanmenxia => ("三门峡", "河南"),
    Nanyang => ("南阳", "河南"),
    Shangqiu => ("商丘", "河南"),
    Xinyang => ("信阳", "河南"),
    Zhoukou => ("周口", "河南"),
    Zhumadian => ("驻马店", "河南"),
    // 湖北
    Wuhan => ("武汉", "湖北"),
    Huangshi => ("黄石", "湖北"),
    Shiyan => ("十堰", "湖北"),
    Yichang => ("宜昌", "湖北"),
    Xiangyang => ("襄阳", "湖北"),
    Ezhou => ("鄂州", "湖北"),
    Jingmen => ("荆门", "湖北"),
    Xiaogan => ("孝感", "湖北"),
    Jingzhou => ("荆州", "湖北"),
    Huanggang => ("黄冈", "湖北"),
    Xianning => ("咸宁", "湖北"),
    Suizhou => ("随州", "湖北"),
    // 湖南
    Changsha => ("长沙", "湖南"),
    Zhuzhou => ("株洲", "湖南"),
    Xiangtan => ("湘潭", "湖南"),
    Hengyang => ("衡阳", "湖南"),
    Shaoyang => ("邵阳", "湖南"),
    Yueyang => ("岳阳", "湖南"),
    Changde => ("常德", "湖南"),
    Zhangjiajie => ("张家界", "湖南"),
    Yiyang => ("益阳", "湖南"),
    Chenzhou => ("郴州", "湖南"),
    Yongzhou => ("永州", "湖南"),
    Huaihua => ("怀化", "湖南"),
    Loudi => ("娄底", "湖南"),
    // 广东
    Guangzhou => ("广州", "广东"),
    Shaoguan => ("韶关", "广东"),
    Shenzhen => ("深圳", "广东"),
    Zhuhai => ("珠海", "广东"),
    Shantou => ("汕头", "广东"),
    Foshan => ("佛山", "广东"),
    Jiangmen => ("江门", "广东"),
    Zhanjiang => ("湛江", "广东"),
    Maoming => ("茂名", "广东"),
    Zhaoqing => ("肇庆", "广东"),
    Huizhou => ("惠州", "广东"),
    Meizhou => ("梅州", "广东"),
    Shanwei => ("汕尾", "广东"),
    Heyuan => ("河源", "广东"),
    Yangjiang => ("阳江", "广东"),
    Qingyuan => ("清远", "广东"),
    Dongguan => ("东莞", "广东"),
    Zhongshan => ("中山", "广东"),
    Chaozhou => ("潮州", "广东"),
    Jieyang => ("揭阳", "广东"),
    Yunfu => ("云浮", "广东"),
    // 广西
    Nanning => ("南宁", "广西"),
    Liuzhou => ("柳州", "广西"),
    Guilin => ("桂林", "广西"),
    Wuzhou => ("梧州", "广西"),
    Beihai => ("北海", "广西"),
    Fangchenggang => ("防城港", "广西"),
    Qinzhou => ("钦州", "广西"),
    Guigang => ("贵港", "广西"),
    Yulin => ("玉林", "广西"),
    Baise => ("百色", "广西"),
    Hezhou => ("贺州", "广西"),
    Hechi => ("河池", "广西"),
    Laibin => ("来宾", "广西"),
    Chongzuo => ("崇左", "广西"),
    // 海南
    Haikou => ("海口", "海南"),
    Sanya => ("三亚", "海南"),
    Sansha => ("三沙", "海南"),
    Danzhou => ("儋州", "海南"),
    // 四川
    Chengdu => ("成都", "四川"),
    Zigong => ("自贡", "四川"),
    Panzhihua => ("攀枝花", "四川"),
    Luzhou => ("泸州", "四川"),
    Deyang => ("德阳", "四川"),
    Mianyang => ("绵阳", "四川"),
    Guangyuan => ("广元", "四川"),
    Suining => ("遂宁", "四川"),
    Neijiang => ("内江", "四川"),
    Leshan => ("乐山", "四川"),
    Nanchong => ("南充", "四川"),
    Meishan => ("眉山", "四川"),
    Yibin => ("宜宾", "四川"),
    Guangan => ("广安", "四川"),
    Dazhou => ("达州", "四川"),
    Yaan => ("雅安", "四川"),
    Bazhong => ("巴中", "四川"),
    Ziyang => ("资阳", "四川"),
    // 贵州
    Guiyang => ("贵阳", "贵州"),
    Liupanshui => ("六盘水", "贵州"),
    Zunyi => ("遵义", "贵州"),
    Anshun => ("安顺", "贵州"),
    Bijie => ("毕节", "贵州"),
    Tongren => ("铜仁", "贵州"),
    // 云南
    Kunming => ("昆明", "云南"),
    Qujing => ("曲靖", "云南"),
    Yuxi => ("玉溪", "云南"),
    Baoshan => ("保山", "云南"),
    Zhaotong => ("昭通", "云南"),
    Lijiang => ("丽江", "云南"),
    Puer => ("普洱", "云南"),
    Lincang => ("临沧", "云南"),
    // 西藏
    Lhasa => ("拉萨", "西藏"),
    Shigatse => ("日喀则", "西藏"),
    Chamdo => ("昌都", "西藏"),
    Shannan => ("山南", "西藏"),
    Nyingchi => ("林芝", "西藏"),
    // 陕西
    Xian => ("西安", "陕西"),
    Tongchuan => ("铜川", "陕西"),
    Baoji => ("宝鸡", "陕西"),
    Xianyang => ("咸阳", "陕西"),
    Weinan => ("渭南", "陕西"),
    Yanan => ("延安", "陕西"),
    Hanzhong => ("汉中", "陕西"),
    YulinSX => ("榆林", "陕西"),
    Ankang => ("安康", "陕西"),
    Shangluo => ("商洛", "陕西"),
    // 甘肃
    Lanzhou => ("兰州", "甘肃"),
    Jiayuguan => ("嘉峪关", "甘肃"),
    Jinchang => ("金昌", "甘肃"),
    Baiyin => ("白银", "甘肃"),
    Tianshui => ("天水", "甘肃"),
    Wuwei => ("武威", "甘肃"),
    Zhangye => ("张掖", "甘肃"),
    Pingliang => ("平凉", "甘肃"),
    Jiuquan => ("酒泉", "甘肃"),
    Qingyang => ("庆阳", "甘肃"),
    Dingxi => ("定西", "甘肃"),
    Longnan => ("陇南", "甘肃"),
    // 青海
    Xining => ("西宁", "青海"),
    Haidong => ("海东", "青海"),
    // 宁夏
    Yinchuan => ("银川", "宁夏"),
    Shizuishan => ("石嘴山", "宁夏"),
    Wuzhong => ("吴忠", "宁夏"),
    Guyuan => ("固原", "宁夏"),
    Zhongwei => ("中卫", "宁夏"),
    // 新疆
    Urumqi => ("乌鲁木齐", "新疆"),
    Karamay => ("克拉玛依", "新疆"),
    Turpan => ("吐鲁番", "新疆"),
    Hami => ("哈密", "新疆"),
}
